import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  stepCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 12,
  },
  stepContentContainer: {
    marginTop: 8,
    height: "100%",
  },
  stepProgressContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#f9f9f9",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  buildingIndicator: {
    alignItems: "center",
    padding: 5,
    minWidth: 80,
  },
  buildingName: {
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 3,
  },
  progressLine: {
    flex: 1,
    height: 2,
    backgroundColor: "#cccccc",
    marginHorizontal: 5,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  indoorInfoContainer: {
    padding: 15,
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
    marginBottom: 15,
  },
  indoorInfoText: {
    fontSize: 16,
    color: "#333",
    marginBottom: 10,
  },
  indoorDetailsText: {
    fontSize: 14,
    color: "#666",
    lineHeight: 22,
  },
  indoorNavButton: {
    backgroundColor: "#912338",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 15,
  },
  indoorNavButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginRight: 8,
  },
  navigationStartedText: {
    marginTop: 10,
    fontStyle: "italic",
    color: "#666",
    textAlign: "center",
  },
  // Map styles
  mapContainer: {
    height: 200,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#f0f0f0",
    marginBottom: 8,
  },
  mapWrapper: {
    flex: 1,
    borderRadius: 12,
    overflow: "hidden",
  },
  mapWebView: {
    flex: 1,
    backgroundColor: "transparent",
  },
  expandButton: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 8,
    padding: 8,
    zIndex: 10,
  },
  expandButtonText: {
    fontSize: 14,
    color: "#912338",
    fontWeight: "600",
  },
  // Direction list styles
  directionsContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 12,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
    marginTop: 12,
  },
  directionsTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 8,
  },
  directionsList: {
    maxHeight: 200,
  },
  directionItem: {
    flexDirection: "row",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    alignItems: "flex-start",
  },
  directionNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#912338",
    color: "#ffffff",
    textAlign: "center",
    lineHeight: 24,
    marginRight: 12,
    fontWeight: "bold",
  },
  directionContent: {
    flex: 1,
  },
  directionText: {
    fontSize: 15,
    color: "#333333",
    lineHeight: 22,
  },
  distanceText: {
    fontSize: 14,
    color: "#666666",
    marginTop: 4,
  },
  noDirectionsText: {
    fontSize: 16,
    color: "#666666",
    fontStyle: "italic",
    textAlign: "center",
    padding: 16,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  loadingText: {
    marginTop: 10,
    color: "#666666",
    fontSize: 14,
  },
});

export default styles;
