name: ci
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./ConcordiaMaps
        run: npm install

      - name: Lint Code
        working-directory: ./ConcordiaMaps
        run: npm run lint

      - name: Format Code
        working-directory: ./ConcordiaMaps
        run: npx prettier --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./ConcordiaMaps
        run: npm install

      - name: Lint Code
        working-directory: ./ConcordiaMaps
        run: npm run lint

      - name: Format Code
        working-directory: ./ConcordiaMaps
        run: npx prettier --check .

      - name: Run Jest Tests with Coverage
        working-directory: ./ConcordiaMaps
        run: npm run test -- --coverage

      - name: Run SonarQube analysis
        working-directory: ./ConcordiaMaps
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=SOEN-390-pmzone_SOEN-_390-Q-QD \
            -Dsonar.organization=soen-390-pmzone \
            -Dsonar.sources=. \
            -Dsonar.exclusions=**/node_modules/**,**/*.test.js \
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \
            -Dsonar.host.url=https://sonarcloud.io

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy to GitHub Pages
        run: echo "Deploy"
